[tool.poetry]
name = "date-update"
version = "0.1.0"
description = ""
authors = ["alucardthefish <sergiop18@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
sqlalchemy = "^2.0.30"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
